### ISSUE TITLE
2 BTC redeem transaction instead of 1

### ISSUE THREAD

**Issue by aamironov** [interlay/polkabtc-ui#68] opened 2021-03-02 19:03 UTC
**Describe the bug**
I created 1 redeem transaction, but I see 2 transactions in UI with the same request ID.

**To Reproduce**
1. Redeem all BTC
2. Sign
3. Refresh page

**Expected behavior**
1 transaction

**Screenshots**
<img width="1280" alt="Screen Shot 2021-03-02 at 10 55 58 AM" src="https://user-images.githubusercontent.com/16032708/109700551-bf291580-7b46-11eb-808e-b7ecaaf3a165.png">
<img width="1280" alt="Screen Shot 2021-03-02 at 11 00 21 AM" src="https://user-images.githubusercontent.com/16032708/109700555-c18b6f80-7b46-11eb-8061-52a494929571.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aamironov** [comment] 2021-03-02 19:07
Also, I see similar behavior for issuing
<img width="1280" alt="Screen Shot 2021-03-02 at 11 05 30 AM" src="https://user-images.githubusercontent.com/16032708/109701017-66a64800-7b47-11eb-889d-a53c858a3ecd.png">

**Comment by savudani8** [comment] 2021-03-05 14:42
Thanks for reporting! This is a duplicate of https://github.com/interlay/polkabtc-ui/issues/67. Follow that thread for updates

**Closed by savudani8** 2021-03-05 14:42 UTC
