### ISSUE TITLE
duplicate transaction occurs

### ISSUE THREAD

**Issue by rjramesh** [interlay/polkabtc-ui#67] opened 2021-03-02 19:01 UTC
**Describe the bug**
what the bug :     when i working on issue tab after clicking issue button with 0.1 polkabtc after seem history available 2 transcations but i made only 1 

**To Reproduce**
1. Go to  issue option 
2. i made 0.1 polkbtc transction
3. Scroll down and confirm button
4. i see below available 2 transction

**Expected behavior**
when i made only 1 transction then see only 1 historry of that 

**Screenshots**
see here screenshot
https://ibb.co/qdyFCyF

**Desktop (please complete the following information):**
 - OS - windows 10
 - Browser [brave browser]
 - Version [64 bit]

**Additional context**
as i see my transction showing duplicate 1 so reflect 1 more

**Comment by nud3l** [comment] 2021-10-08 12:51
This was caused by an issue in the caching database. Resolved in the latest release.

**Closed by nud3l** 2021-10-08 12:51 UTC
Labels: bug
