### ISSUE TITLE
The problem with the redemption of interBTC after making a large number of redemptions

### ISSUE THREAD

**Issue by meeshkov** [interlay/polkabtc-ui#296] opened 2021-09-17 20:35 UTC
**Describe the bug**
The problem with the withdrawal of tBtc, after conducting about 40 redemptions
![ISSUE#1](https://user-images.githubusercontent.com/90933299/133848118-d74e811e-9d21-4b8a-aeff-ce7ba6a03042.jpg)

The problem is not being solved:
 -After a long time of waiting
 -After page refresh
 -When the withdrawal amount is changed

**Expected behavior**
Hope that my problem will be noticed and accepted for correction by the developers. Always happy to work on improving amazing projects for the crypto community))

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Chrome
 - Version 93.0.4577.63
**Additional context**
@nud3l 
@savudani8

**Comment by nud3l** [comment] 2021-10-05 14:37
We have restarted the testnet. Not sure what this was caused by, but having multiple redeem requests should not cause issues. Closing this for now and see if it pops up again.

**Closed as completed by nud3l** 2021-10-05 14:37 UTC
